### ISSUE TITLE
Specify trusted root/intermediate CA cert for SSL/TSL communication

### ISSUE THREAD

**Issue by Constantin07** [nodevault/node-vault#63]
Hi All,

Is there any way to specify the which RooT/Trusted intermediate CA certificate to use in communication to Vault API endpoint ?

PS: Looking at the code I used VAULT_SKIP_VERIFY=true to avoid checking just for development/testing purposes but in production I need to verify the Vault endpoint is trusted one.

Regards,
Constantin

**Comment by Constantin07** [comment]
Are the VAULT_CACERT and VAULT_CAPATH environment variables supported ?

**Comment by steve-perkins** [comment]
Hi @Constantin07, are you by chance the same Constantine who was facing a similar issue with the other node Vault driver back in March?

https://gitter.im/chiefy/vaulted/archives/2017/03/08

If so, then I am starting to worry that we have the only two Node apps on earth trying to connect with Vault using CA cert verification!

Have you found any solutions or workarounds yet?  I'm to point of eschewing "drivers", and just using low-level REST calls to Vault's HTTP API directly.

**Comment by Constantin07** [comment]
Hi @steve-perkins, unfortunately I'm another Constantin :-)

For testing purposes I tried to use a self signed cert by placing it in the same directory with Node JS code but I get:

```
{ RequestError: Error: self signed certificate in certificate chain
    at new RequestError (/opt/node_modules/request-promise/lib/errors.js:11:15)
    at Request.RP$callback [as _callback] (/opt/node_modules/request-promise/lib/rp.js:60:32)
    at self.callback (/opt/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/opt/node_modules/request/request.js:878:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1277:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  name: 'RequestError',
  message: 'Error: self signed certificate in certificate chain',
  cause: 
   { Error: self signed certificate in certificate chain
       at Error (native)
       at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
       at emitNone (events.js:86:13)
       at TLSSocket.emit (events.js:185:7)
       at TLSSocket._finishInit (_tls_wrap.js:610:8)
       at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38) code: 'SELF_SIGNED_CERT_IN_CHAIN' },
  error: 
   { Error: self signed certificate in certificate chain
       at Error (native)
       at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
       at emitNone (events.js:86:13)
       at TLSSocket.emit (events.js:185:7)
       at TLSSocket._finishInit (_tls_wrap.js:610:8)
       at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38) code: 'SELF_SIGNED_CERT_IN_CHAIN' },
  options: 
   { json: true,
     resolveWithFullResponse: true,
     simple: false,
     strictSSL: true,
     followAllRedirects: true,
     path: '/*******/*******/*******',
     method: 'GET',
     headers: { 'X-Vault-Token': '*************' },
     uri: 'https://****.*****.***:8200/v1/******/****/*********',
     callback: undefined,
     transform: undefined },
  response: undefined }
```

No workaround at the moment yet. I don't have strong Node JS experience but looking at source code it doesn't look to long.

**Comment by DaniGuardiola** [comment]
I will try to fix this in the future.

**Comment by alexraddas** [comment]
`var fs = require('fs');
var options = {
  apiVersion: 'v1',
  endpoint: 'https://127.0.0.1',
  token: '0123456789',
  requestOptions: {
    ca: fs.readFileSync('/etc/ssl/certs/cabundlefile.crt'),
  }
};

var vault = require("node-vault")(options);`

**Comment by AidanWelch** [comment]
@alexraddas do you know what the accepted encoding formats for that option are?

**Comment by araddas** [comment]
> @alexraddas do you know what the accepted encoding formats for that option are?

Since node-vault is based on the request-promise module, it would be dependent on which formats are supported by request-promise. For my specific use case its x509 PEM. You can always convert your CA bundle to another format using openssl. https://www.sslshopper.com/article-most-common-openssl-commands.html.

**Comment by GeorgePals** [comment]
Hello!

I've tried to connect nodejs with Vault, over SSL, but nothing seems to work.

Vault's debug output is:
`somevaultaddr.com    | 2021-01-18T16:43:10.055Z [INFO]  http: TLS handshake error from 192.168.128.1:45578: EOF`

and from node I receive:
` 
   at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8) {
  cause: Error: **unable to verify the first certificate**
      at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
      at TLSSocket.emit (events.js:315:20)
      at TLSSocket._finishInit (_tls_wrap.js:932:8)
      at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12) {
    code: '**UNABLE_TO_VERIFY_LEAF_SIGNATURE**'
  },
  error: Error: unable to verify the first certificate
      at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
      at TLSSocket.emit (events.js:315:20)
      at TLSSocket._finishInit (_tls_wrap.js:932:8)
      at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12) {
    code: '**UNABLE_TO_VERIFY_LEAF_SIGNATURE**'
`
What I've tried:

- Adding root CA's cert to Node
- [alexraddas post](https://github.com/kr1sp1n/node-vault/issues/63#issuecomment-385707270)
- Checked if vault's certs are okay - They seem to be okay!
- Whatever else I could think that could help =/

Any suggestions?

Thanks in advance!

**Comment by aviadhahami** [comment]
Request-promise will be changed soon in favor of another (see #150)
I will have this in mind for when we will select the correct solution.

Closing the issue for now

**Comment by aviadhahami** [comment]
Feature request -> allow settings root/intermediate CA cert
